// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYdp4Z22Ec26tYhclpkWUXsbsLkgLKQ7U',
    appId: '1:181175421533:web:05d31e6e820847f3079bb4',
    messagingSenderId: '181175421533',
    projectId: 'exp-8-b4788',
    authDomain: 'exp-8-b4788.firebaseapp.com',
    storageBucket: 'exp-8-b4788.firebasestorage.app',
    measurementId: 'G-K7RTZ4R9BC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdqX6mB6lcoMmXEe62jw0nbG6qh1hsQHo',
    appId: '1:181175421533:android:56c818c185038a94079bb4',
    messagingSenderId: '181175421533',
    projectId: 'exp-8-b4788',
    storageBucket: 'exp-8-b4788.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkYQwO2LZtHHYeBkZbJNcd_YsGTVuXLN8',
    appId: '1:181175421533:ios:047b9d6fad88bf98079bb4',
    messagingSenderId: '181175421533',
    projectId: 'exp-8-b4788',
    storageBucket: 'exp-8-b4788.firebasestorage.app',
    iosBundleId: 'com.example.exp5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkYQwO2LZtHHYeBkZbJNcd_YsGTVuXLN8',
    appId: '1:181175421533:ios:047b9d6fad88bf98079bb4',
    messagingSenderId: '181175421533',
    projectId: 'exp-8-b4788',
    storageBucket: 'exp-8-b4788.firebasestorage.app',
    iosBundleId: 'com.example.exp5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYdp4Z22Ec26tYhclpkWUXsbsLkgLKQ7U',
    appId: '1:181175421533:web:70e2f2963a77d1e1079bb4',
    messagingSenderId: '181175421533',
    projectId: 'exp-8-b4788',
    authDomain: 'exp-8-b4788.firebaseapp.com',
    storageBucket: 'exp-8-b4788.firebasestorage.app',
    measurementId: 'G-X77GSV5V37',
  );

}