// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlrQsNnLmweHomi5rgRjhvjWpCligXlmY',
    appId: '1:882581920721:web:e27ef7cac43fe06ea75ef0',
    messagingSenderId: '882581920721',
    projectId: 'exp-9-47040',
    authDomain: 'exp-9-47040.firebaseapp.com',
    storageBucket: 'exp-9-47040.firebasestorage.app',
    measurementId: 'G-1EBBGBJ79C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw4nywABsbSuhJZOVSXlwvSkcmnEkCNUY',
    appId: '1:882581920721:android:ba9ba7d93ff68d8ba75ef0',
    messagingSenderId: '882581920721',
    projectId: 'exp-9-47040',
    storageBucket: 'exp-9-47040.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuMjzVZA_XRHy6Dg-FSHov7FxGzjXwMN0',
    appId: '1:882581920721:ios:2bac5791c53d14caa75ef0',
    messagingSenderId: '882581920721',
    projectId: 'exp-9-47040',
    storageBucket: 'exp-9-47040.firebasestorage.app',
    iosBundleId: 'com.example.exp9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuMjzVZA_XRHy6Dg-FSHov7FxGzjXwMN0',
    appId: '1:882581920721:ios:2bac5791c53d14caa75ef0',
    messagingSenderId: '882581920721',
    projectId: 'exp-9-47040',
    storageBucket: 'exp-9-47040.firebasestorage.app',
    iosBundleId: 'com.example.exp9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlrQsNnLmweHomi5rgRjhvjWpCligXlmY',
    appId: '1:882581920721:web:1134f73d12a953a4a75ef0',
    messagingSenderId: '882581920721',
    projectId: 'exp-9-47040',
    authDomain: 'exp-9-47040.firebaseapp.com',
    storageBucket: 'exp-9-47040.firebasestorage.app',
    measurementId: 'G-PF5SS1CGQH',
  );

}